### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by Mexiswow** [Gagauz2010/WOWLauncher#1]
Добрый день,

скачал дистрибутив, запустил через VS 2015 и сразу без изменений попробывал скомпилировать. Выдало ошибку при компиляции:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0136	A local or parameter named 'ex' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter	Launcher	C:\projects\WOWLauncher-master\Launcher\MainWindow.xaml.cs	478	Active

Не знаете в чём может быть проблема?

**Comment by Mexiswow** [comment]
Не получилось в Launcher, а вот Distribute Updates компиляция прошла без проблем!

**Comment by Gagauz2010** [comment]
Исправлено
