### ISSUE TITLE
Launcher 8.x.x

### ISSUE THREAD

**Issue by ReyDonovan** [Gagauz2010/WOWLauncher#2]
приятно видеть русских нет в планах сделать данный Лаучер для версии BfA совместно с (патчером) чтоб отключить конект к Blizz

**Comment by Gagauz2010** [comment]
Привет. Если честно были планы по общей модернизации текущего инструментария (рефакторинг + переход на JSON формат для списков), на актуализацию под последние версии клиента они были ещё раньше.

Как видишь ничего из этого не сделано и вряд ли будет. После работы просто хочется банально отдохнуть, а не продолжать кодить. Если есть особое желание, то можешь попробовать самостоятельно найти на просторах интернета возможное решение.

С наилучшими пожеланиями, Сергей Гагауз!

On Dec 6, 2018, at 11:19, ReyDonovan <notifications@github.com<mailto:notifications@github.com>> wrote:


приятно видеть русских нет в планах сделать данный Лаучер для версии BfA совместно с (патчером) чтоб отключить конект к Blizz
