### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ctmwow** [Gagauz2010/WOWLauncher#3]
Are you interested in upgrading the project to a Blizzard-like one?
Your Animations is very cool.
I'm trying to do this from your project, although I'm a layman.  :D

**Comment by Gagauz2010** [comment]
**Greetings**!

I have not been engaged in further development and promotion of the project for a long time. Most likely, it will remain at the current stage, including only the basic functionality (as it was originally intended).

The publication of the code was conceived as a basis for continuing self-development by others or using only the update system.

**P.S.** I am very grateful for your interest in improving the software.

**Comment by ctmwow** [comment]
I tried to modify your ui, but I found that WPF was too difficult for me.
Can you help me modify the look of Battle Net? I will continue to do the internal functions, and I will add the server core.
I sent you an email the other day
