### ISSUE TITLE
Ошибка 404

### ISSUE THREAD

**Issue by avatar789** [Gagauz2010/WOWLauncher#4]
Приветствую при сборке проекта выдаёт такую ошибку
![image](https://user-images.githubusercontent.com/5444058/71779852-fce6e880-2fec-11ea-8a14-69d996eca789.png)
Ссылки к которым пытается приконектится доступны если заходить через браузер.
Никаких изменений в ваш код не вносилось абсолютно только поправил ссылки в окне properites

**Comment by Gagauz2010** [comment]
Приветствую. Спасибо за терпение. Праздники удались!)

Пришлось проверить все ссылки руками. И вот результат проверки.

<img width="827" alt="Screen Shot 2020-01-09 at 15 34 19" src="https://user-images.githubusercontent.com/5500657/72071919-8c461180-32f5-11ea-8b25-8c09a529820c.png">
